Repository TECHOUS/codemash, pull requests merged in 2024-10, with the labels that each got.

#105 Completed the basic Search section for mobile
  package.json
  src/components/App/App.jsx
  src/components/RatingPopup/RatingPopupContainer.jsx
  src/components/SearchSection/ContributionGuidelines/ContributionGuidelines.jsx
  src/components/SearchSection/ContributionGuidelines/ContributionGuidelines.module.css
  src/components/SearchSection/ContributionGuidelines/ContributionGuidelinesContainer.jsx
  src/components/SearchSection/ContributionGuidelines/ContributionGuidelinesContainer.module.css
  src/components/SearchSection/ContributionGuidelines/index.js
  src/components/SearchSection/ResponseCards/ResponseCard/CardContent/CardContent.jsx
  src/components/SearchSection/ResponseCards/ResponseCard/CardContent/CardContent.module.css
  src/components/SearchSection/ResponseCards/ResponseCard/CardContent/index.js
  src/components/SearchSection/ResponseCards/ResponseCard/ResponseCard.jsx
  src/components/SearchSection/ResponseCards/ResponseCard/ResponseCard.module.css
  src/components/SearchSection/ResponseCards/ResponseCards.jsx
  src/components/SearchSection/ResponseCards/ResponseCardsContainer.jsx
  src/components/SearchSection/ResponseCards/index.js
  src/components/SearchSection/ResponseHandler/ResponseHandler.jsx
  src/components/SearchSection/ResponseHandler/ResponseHandler.module.css
  src/components/SearchSection/ScoreImoji/ScoreImoji.jsx
  src/components/SearchSection/ScoreImoji/ScoreImoji.module.css
  src/components/SearchSection/ScoreImoji/ScoreImojiContainer.jsx
  src/components/SearchSection/ScoreImoji/ScoreImojiContainer.module.css
  src/components/SearchSection/ScoreImoji/index.js
  src/components/SearchSection/ScoreReactionBoard/SRBCrossIcon/SRBCrossIcon.jsx
  src/components/SearchSection/ScoreReactionBoard/SRBCrossIcon/SRBCrossIcon.module.css
  src/components/SearchSection/ScoreReactionBoard/SRBCrossIcon/index.js
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionBoardContainer.jsx
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionBoardHandler.jsx
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionBoardPresenter.jsx
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionBoardPresenter.module.css
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionTable/SRTableRows/SRTableData/SRTableData.jsx
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionTable/SRTableRows/SRTableData/SRTableData.module.css
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionTable/SRTableRows/SRTableData/index.js
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionTable/SRTableRows/SRTableRow/SRTableRow.jsx
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionTable/SRTableRows/SRTableRow/index.js
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionTable/SRTableRows/SRTableRows.jsx
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionTable/SRTableRows/index.js
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionTable/ScoreReactionTable.jsx
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionTable/ScoreReactionTable.module.css
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionTable/index.js
  src/components/SearchSection/ScoreReactionBoard/index.js
  src/components/SearchSection/SearchBar/SearchBar.jsx
  src/components/SearchSection/SearchBar/SearchBar.module.css
  src/components/SearchSection/SearchSectionContainer.jsx
  src/components/SearchSection/SearchSectionPresenter.jsx
  src/components/SearchSection/SearchSectionPresenter.module.css
  src/components/SearchSection/index.js
  src/components/hooks/useRandomCodesAPI.js
  src/components/hooks/useSearchSectionReducer.js
  src/components/hooks/useSearchUserAPI.js
  yarn.lock
Labels: enhancement, hacktoberfest-accepted, Hacktoberfest24

#107 add TwoSum solution
  CodeBase/TwoSum.js
Labels: hacktoberfest-accepted, JavaScript, Hacktoberfest24

#110 MERGE SORT ALGORITHM
  CodeBase/merge_sort.cpp
Labels: hacktoberfest-accepted, C++, Hacktoberfest24

#114 Quick Sort Algorithm
  CodeBase/Quick_Sort.cpp
Labels: hacktoberfest-accepted, C++, Hacktoberfest24

#116 Added Algorithm for Radix Sort
  CodeBase/Radix_Sort.java
Labels: hacktoberfest-accepted, JAVA, Hacktoberfest24

#118 Responsiveness and fixes for search section
  src/components/RatingPopup/RatingPopupPresenter.module.css
  src/components/SearchSection/ContributionGuidelines/ContributionGuidelinesContainer.module.css
  src/components/SearchSection/ResponseCards/ResponseCard/ResponseCard.module.css
  src/components/SearchSection/ScoreImoji/ScoreImojiContainer.module.css
  src/components/SearchSection/ScoreReactionBoard/SRBCrossIcon/SRBCrossIcon.module.css
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionBoardPresenter.module.css
  src/components/SearchSection/ScoreReactionBoard/ScoreReactionTable/SRTableRows/SRTableData/SRTableData.module.css
  src/components/SearchSection/SearchBar/SearchBar.module.css
  src/components/SearchSection/SearchSectionPresenter.module.css
Labels: hacktoberfest-accepted, react, Hacktoberfest24

#117 bubble sort code
  CodeBase/Bubble_sort.cpp
Labels: hacktoberfest-accepted, C++, Hacktoberfest24

#119 Navigation fixes for the landing page
  src/components/App/App.jsx
  src/components/Header/Header.jsx
  src/components/Header/HeaderLinks/HeaderLink/HeaderLink.jsx
  src/components/Header/HeaderLinks/HeaderLinks.jsx
  src/components/LandingSection/bottom/LandingSectionBottom.jsx
  src/components/SearchSection/SearchSectionPresenter.jsx
  src/components/hooks/useSearchUserAPI.js
  src/index.css
Labels: hacktoberfest-accepted, react, Hacktoberfest24

#120 Landing page Responsive UI fixes
  src/components/LandingSection/LandingSection.css
  src/components/RatingPopup/DoneButton/DoneButtonContainer.module.css
  src/components/RatingPopup/RPCrossIcon/RPCrossIcon.module.css
  src/components/RatingPopup/RatingPopupPresenter.module.css
  src/components/RatingPopup/RatingPopupViewContent/RPDesktopContentViewer/RPDCodeObject/RPDCodeObject.module.css
  src/components/RatingPopup/RatingPopupViewContent/RPMobileContentViewer/RPMCodeViewer/RPMCodeViewer.module.css
  src/components/RatingPopup/RatingPopupViewContent/StarComponent/EmptyStar/EmptyStar.jsx
  src/components/RatingPopup/RatingPopupViewContent/StarComponent/EmptyStar/EmptyStar.module.css
  src/components/RatingPopup/RatingPopupViewContent/StarComponent/SolidStar/SolidStar.jsx
  src/components/RatingPopup/RatingPopupViewContent/StarComponent/SolidStar/SolidStar.module.css
  src/components/ToastMessages/ToastMessagesContainer.module.css
Labels: bug, hacktoberfest-accepted, react, Hacktoberfest24
